### ISSUE TITLE
Update service stays in a loop trying to install obsoletes or non accessible docker images.

### ISSUE THREAD

**Issue by githule** [CybercentreCanada/assemblyline#219]
**Describe the bug**
Update service stays in a loop trying to install obsoletes or non accessible docker images.

**To Reproduce**
1. Run a v4.4 instance
2. Upgrade releases in env file
3. Rerun docker compose down, docker compose up -d --wait
4. Go to Service
5. Click on Update All
6. See error : Updater container loops in deploying previously activated and now inaccessible services (cuckoo, hatching)

**Expected behavior**
If update is not accessible, service should stop being updated however it received instruction to install everything
Admin must be able to break massive upgrade loop via purging some cache or clearing pending action

**Logs**
```
al-updater-1  | 2024-04-24 14:27:16,809  WARNING b5d37c8093a8 1             assemblyline.service.updater | Restarting thread: Container installs
al-updater-1  | 2024-04-24 14:27:16,809     INFO b5d37c8093a8 1             assemblyline.service.updater | Starting thread: Container installs
al-updater-1  | 2024-04-24 14:27:16,810     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Installing all services marked for install...
al-updater-1  | 2024-04-24 14:27:18,149     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Latest Batchdeobfuscator tag on STABLE channel is: 4.5.0.stable11
al-updater-1  | 2024-04-24 14:27:18,149     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Service Batchdeobfuscator is being installed to version 4.5.0.stable11...
al-updater-1  | 2024-04-24 14:27:18,193     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Latest APKaye tag on STABLE channel is: 4.5.0.stable5
al-updater-1  | 2024-04-24 14:27:18,193     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Service APKaye is being installed to version 4.5.0.stable5...
al-updater-1  | 2024-04-24 14:27:18,806     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Latest Swiffer tag on STABLE channel is: 4.5.0.stable5
al-updater-1  | 2024-04-24 14:27:18,806     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Service Swiffer is being installed to version 4.5.0.stable5...
al-updater-1  | 2024-04-24 14:27:19,294  WARNING b5d37c8093a8 1             assemblyline.service.updater | [CI] Cannot fetch latest tag for service Cuckoo - cccs/assemblyline-service-cuckoo => [server: registry.hub.docker.com, repo_na
me: cccs/assemblyline-service-cuckoo, channel: stable]
al-updater-1  | 2024-04-24 14:27:19,294     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Service Cuckoo is being installed to version None...
al-updater-1  | 2024-04-24 14:27:27,017    ERROR b5d37c8093a8 1             assemblyline.service.updater | [CI] Service Cuckoo has failed to install. Install procedure cancelled... [404 Client Error for http+docker://localhost/v1.43/i
mages/create?tag=None&fromImage=cccs%2Fassemblyline-service-cuckoo: Not Found ("manifest for cccs/assemblyline-service-cuckoo:None not found: manifest unknown: manifest unknown")]
al-updater-1  | 2024-04-24 14:27:33,288  WARNING b5d37c8093a8 1             assemblyline.service.updater | [CI] Cannot fetch latest tag for service Hatching - ghcr.io/usaa/assemblyline-service-hatching-triage => [server: registry.hub.
docker.com, repo_name: ghcr.io/usaa/assemblyline-service-hatching-triage, channel: stable]
al-updater-1  | 2024-04-24 14:27:36,802     INFO b5d37c8093a8 1             assemblyline.service.updater | [CU] Updating all services marked for update...
al-updater-1  | 2024-04-24 14:27:36,816     INFO b5d37c8093a8 1             assemblyline.service.updater | [CU] Done updating services, waiting 60 seconds for next update...
al-updater-1  | 2024-04-24 14:27:49,294     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Service Hatching is being installed to version None...
al-updater-1  | 2024-04-24 14:28:36,817     INFO b5d37c8093a8 1             assemblyline.service.updater | [CU] Updating all services marked for update...                                                                                
al-updater-1  | 2024-04-24 14:28:36,821     INFO b5d37c8093a8 1             assemblyline.service.updater | [CU] Done updating services, waiting 60 seconds for next update...
al-updater-1  | 2024-04-24 14:28:50,326    ERROR b5d37c8093a8 1             assemblyline.service.updater | [CI] Service Hatching has failed to install. Install procedure cancelled... [500 Server Error for http+docker://localhost/v1.43
/images/create?tag=None&fromImage=ghcr.io%2Fusaa%2Fassemblyline-service-hatching-triage: Internal Server Error ("manifest unknown")]                                                                                                      
al-updater-1  | 2024-04-24 14:28:55,326    ERROR b5d37c8093a8 1             assemblyline.service.updater | Crash in dispatcher: container_installs
al-updater-1  | Traceback (most recent call last):                                                                                                                                                                                        
al-updater-1  |   File "/var/lib/assemblyline/.local/lib/python3.11/site-packages/assemblyline_core/server_base.py", line 275, in with_logs
al-updater-1  |     fn(*args, **kwargs)
al-updater-1  |   File "/var/lib/assemblyline/.local/lib/python3.11/site-packages/assemblyline_core/updater/run_updater.py", line 534, in container_installs
al-updater-1  |     service_name, latest_tag = service_key.split("_")
al-updater-1  |                                ^^^^^^^^^^^^^^^^^
al-updater-1  | AttributeError: 'NoneType' object has no attribute 'split'
al-updater-1  | 2024-04-24 14:28:56,839  WARNING b5d37c8093a8 1             assemblyline.service.updater | Restarting thread: Container installs
al-updater-1  | 2024-04-24 14:28:56,839     INFO b5d37c8093a8 1             assemblyline.service.updater | Starting thread: Container installs
al-updater-1  | 2024-04-24 14:28:56,839     INFO b5d37c8093a8 1             assemblyline.service.updater | [CI] Installing all services marked for install...

```

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.0 upgraded to 4.5.0 (stable)
 - Docker Standelone appliance.

With no success tried to :
- force pull docker images
- find similar issues
- find config options to find a workaround

Thank you for your help,

**Comment by cccs-rs** [comment]
This should be patched in the [4.5.0.20](https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable20) release of Assemblyline.
