### ISSUE TITLE
r.includes is not a function static/js/main.88d31254.js:2:3011566

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#79]
**Describe the bug**
One of our submissions is showing there is a bug here with "r.includes is not a function" "static/js/main.88d31254.js:2:3011566"

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.0.21
 - Browser: Edge

TypeError: r.includes is not a function
    at b5 (https:///static/js/main.88d31254.js:2:3011566)
    at ya (https:///static/js/main.88d31254.js:2:337150)
    at ws (https:///static/js/main.88d31254.js:2:348838)
    at ys (https:///static/js/main.88d31254.js:2:348044)
    at xs (https:///static/js/main.88d31254.js:2:347646)
    at xc (https:///static/js/main.88d31254.js:2:397730)
    at Ol (https:///static/js/main.88d31254.js:2:383326)
    at zl (https:///static/js/main.88d31254.js:2:383254)
    at Ml (https:///static/js/main.88d31254.js:2:383117)
    at ol (https:///static/js/main.88d31254.js:2:379897)

let me know if you need more infromation?

**Comment by cccs-sgaron** [comment]
This issue will be fixed by this: https://github.com/CybercentreCanada/assemblyline-ui-frontend/pull/640

Build 4.4.0.23 with that fix will come in shortly.
